refactor: entities and VO
netordot/PetFamily pull request #11
Opened 2024-09-29 05:49 UTC by netordot

2024-09-29 08:06 UTC, KirillSachkov requested changes

2024-09-29 08:06 UTC, KirillSachkov commented on backend/src/PetFamily.Application/Volunteers/CreateVolunteer/CreateVolunteerService.cs
> +            new Requisites(createVolunteerRequest.Requisites.Select(r => Requisite.Create(r.Title, r.Description).Value).ToList());
А если здесь будут ошибки? Необходимо проверить результат на ошибки

2024-09-29 08:06 UTC, KirillSachkov commented on backend/src/PetFamily.Application/Volunteers/CreateVolunteer/CreateVolunteerService.cs
> +            new VolunteerDetails(createVolunteerRequest.SocialNetworks.Select(s => Social.Create(s.Name, s.Link).Value).ToList());
здесь также

2024-09-29 08:06 UTC, KirillSachkov commented on backend/src/PetFamily.Domain/Pet/Species/Species.cs
> +        if (id == null)
id не может быть здесь null

2024-09-29 08:06 UTC, KirillSachkov commented on backend/src/PetFamily.Domain/Pet/Species/SpeciesId.cs
> +    public Guid Value { get; private set; }
у VO не может быть сеттеров. Изменить класс на record, т.к это VO, везде это поправить

2024-09-29 12:00 UTC, netordot commented on backend/src/PetFamily.Application/Volunteers/CreateVolunteer/CreateVolunteerService.cs
> +            new VolunteerDetails(createVolunteerRequest.SocialNetworks.Select(s => Social.Create(s.Name, s.Link).Value).ToList());
немного не понимаю как в этом случае валидировать список, при входе он nullable, остается разве что валидировать сами элементы списка

2024-09-30 08:50 UTC, KirillSachkov approved these changes

2024-09-30 08:51 UTC, merged